universe = vanilla
getenv = true
executable = /home/bkhatri/STScI_pantheon/data_collection_files/data_collection_Hubble.py
notification = Never
priority = 0
transfer_executable = true
should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT
hold = false
log = /home/bkhatri/STScI_pantheon/logs/test.txt.job/condor_$(Cluster).log
output = /home/bkhatri/STScI_pantheon/logs/test.txt.job/stdout_$(Cluster)_$(Process).log
error = /home/bkhatri/STScI_pantheon/logs/test.txt.job/stderr_$(Cluster)_$(Process).log

arguments = "test.txt"
queue 
